services:
  node1:
    image: blockchain_image
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
      - TEMPLATES_AUTO_RELOAD=True
    network_mode: "host"  # Connect container directly to the host's network